module.exports = {
  env: {
    browser: true,
    es2022: true,
  },
  extends: [
    'eslint:recommended',
  ],
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  globals: {
    // Browser globals
    window: 'readonly',
    document: 'readonly',
    navigator: 'readonly',
    localStorage: 'readonly',
    sessionStorage: 'readonly',
    fetch: 'readonly',
    Headers: 'readonly',
    Request: 'readonly',
    Response: 'readonly',
    FormData: 'readonly',
    Blob: 'readonly',
    File: 'readonly',
    URL: 'readonly',
    URLSearchParams: 'readonly',
    crypto: 'readonly',
    console: 'readonly',
    setTimeout: 'readonly',
    clearTimeout: 'readonly',
    setInterval: 'readonly',
    clearInterval: 'readonly',
    addEventListener: 'readonly',
    removeEventListener: 'readonly',
    // Custom globals
    t: 'readonly',
    LANG: 'readonly',
    T: 'readonly',
    PERMS: 'readonly',
    APP_SETTINGS: 'readonly',
    CSRF_TOKEN: 'readonly',
    api: 'readonly',
    showToast: 'readonly',
    formatMoney: 'readonly',
    formatNumber: 'readonly',
    formatDate: 'readonly',
    escapeHtml: 'readonly',
    canAction: 'readonly',
    animateCount: 'readonly',
    PagedList: 'readonly',
    VALUE_LABELS: 'readonly',
    tv: 'readonly',
    downloadPDF: 'readonly',
    exportCSV: 'readonly',
  },
  rules: {
    'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    'no-undef': 'warn',
    'no-console': 'off',
    'no-alert': 'warn',
    'no-eval': 'error',
    'no-implied-eval': 'error',
    'no-new-func': 'error',
    'no-script-url': 'warn',
    'prefer-const': 'error',
    'no-var': 'error',
    'prefer-arrow-callback': 'warn',
    'arrow-spacing': 'warn',
    'no-duplicate-imports': 'error',
    'object-shorthand': 'warn',
    'prefer-template': 'warn',
  },
};