# -*- coding: utf-8 -*-
"""Professional plan data for the licensing system."""

PLANS = [
    {
        "code": "starter",
        "name": "Starter",
        "name_ar": "المبتدئ",
        "description": "Perfect for small startups and freelancers",
        "description_ar": "مثالية للمشاريع الناشئة والأفراد",
        "max_users": 3,
        "max_projects": 5,
        "max_storage_mb": 512,
        "price_monthly": 99,
        "price_yearly": 990,
        "modules": {
            "accounting": True,
            "projects": False,
            "procurement": False,
            "inventory": False,
            "hr": False,
            "payroll": False,
            "equipment": False,
            "advanced_reports": False,
            "multi_branch": False,
            "api_access": False,
            "priority_support": False,
        },
        "badge": " ",
        "badge_color": "#6366f1",
        "badge_bg": "#eef2ff",
        "icon": " ",
        "gradient": "linear-gradient(135deg, #6366f1, #8b5cf6)",
        "sort_order": 1,
    },
    {
        "code": "basic",
        "name": "Basic",
        "name_ar": "الأساسية",
        "description": "For growing businesses with basic needs",
        "description_ar": "للشركات النامية ذات الاحتياجات الأساسية",
        "max_users": 10,
        "max_projects": 25,
        "max_storage_mb": 2048,
        "price_monthly": 299,
        "price_yearly": 2990,
        "modules": {
            "accounting": True,
            "projects": True,
            "procurement": True,
            "inventory": True,
            "hr": False,
            "payroll": False,
            "equipment": False,
            "advanced_reports": False,
            "multi_branch": False,
            "api_access": False,
            "priority_support": False,
        },
        "badge": " ",
        "badge_color": "#2563eb",
        "badge_bg": "#eff6ff",
        "icon": " ",
        "gradient": "linear-gradient(135deg, #2563eb, #3b82f6)",
        "sort_order": 2,
    },
    {
        "code": "professional",
        "name": "Professional",
        "name_ar": "الاحترافية",
        "description": "Advanced features for established companies",
        "description_ar": "ميزات متقدمة للشركات الراسخة",
        "max_users": 50,
        "max_projects": -1,
        "max_storage_mb": 10240,
        "price_monthly": 799,
        "price_yearly": 7990,
        "modules": {
            "accounting": True,
            "projects": True,
            "procurement": True,
            "inventory": True,
            "hr": True,
            "payroll": True,
            "equipment": True,
            "advanced_reports": True,
            "multi_branch": True,
            "api_access": False,
            "priority_support": False,
        },
        "badge": " ",
        "badge_color": "#059669",
        "badge_bg": "#ecfdf5",
        "icon": " ",
        "gradient": "linear-gradient(135deg, #059669, #10b981)",
        "sort_order": 3,
    },
    {
        "code": "enterprise",
        "name": "Enterprise",
        "name_ar": "المؤسسات",
        "description": "Complete solution for large organizations",
        "description_ar": "حل متكامل للمؤسسات الكبيرة",
        "max_users": 200,
        "max_projects": -1,
        "max_storage_mb": 51200,
        "price_monthly": 1999,
        "price_yearly": 19990,
        "modules": {
            "accounting": True,
            "projects": True,
            "procurement": True,
            "inventory": True,
            "hr": True,
            "payroll": True,
            "equipment": True,
            "advanced_reports": True,
            "multi_branch": True,
            "api_access": True,
            "priority_support": True,
        },
        "badge": "⭐ Most Popular",
        "badge_color": "#d97706",
        "badge_bg": "#fffbeb",
        "icon": " ",
        "gradient": "linear-gradient(135deg, #d97706, #f59e0b)",
        "sort_order": 4,
    },
    {
        "code": "ultimate",
        "name": "Ultimate",
        "name_ar": "المتقدمة",
        "description": "White-glove service with custom integrations",
        "description_ar": "خدمة متكاملة مع تكاملات مخصصة",
        "max_users": -1,
        "max_projects": -1,
        "max_storage_mb": 102400,
        "price_monthly": 4999,
        "price_yearly": 49990,
        "modules": {
            "accounting": True,
            "projects": True,
            "procurement": True,
            "inventory": True,
            "hr": True,
            "payroll": True,
            "equipment": True,
            "advanced_reports": True,
            "multi_branch": True,
            "api_access": True,
            "priority_support": True,
        },
        "badge": " ",
        "badge_color": "#7c3aed",
        "badge_bg": "#f5f3ff",
        "icon": " ",
        "gradient": "linear-gradient(135deg, #7c3aed, #a855f7)",
        "sort_order": 5,
    },
]

GRACE_PERIOD_DAYS = 7
TRIAL_DAYS = 14
